//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modern_Pentathlon_Event_Manager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class appDBEntities : DbContext
    {
        public appDBEntities()
            : base("name=appDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Club> Club { get; set; }
        public virtual DbSet<Competitions> Competitions { get; set; }
        public virtual DbSet<EventCompetitions> EventCompetitions { get; set; }
        public virtual DbSet<EventParticipants> EventParticipants { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Nation> Nation { get; set; }
        public virtual DbSet<Participant> Participant { get; set; }
        public virtual DbSet<Regions> Regions { get; set; }
        public virtual DbSet<Scores> Scores { get; set; }
        public virtual DbSet<Sex> Sex { get; set; }
        public virtual DbSet<StartOrders> StartOrders { get; set; }
    }
}
